all:
  vars:
    app_name: itemsim-server
    app_port: 80
    docker_image_name: "{{ lookup('env', 'DOCKER_IMAGE_NAME', default=Undefined) }}"
    docker_tag: "{{ lookup('env', 'DOCKER_TAG', default='latest') }}"
    docker_digest: "{{ lookup('env', 'DOCKER_DIGEST', default=Undefined) }}"
    deploy_path: /opt/itemsim-server
    env_file: ".env"
